### ISSUE TITLE
Adding to a collection with Github storage has a file naming bug

### ISSUE THREAD

**Issue by revgum** [lumeland/cms#10]
I've tried configuring the `storage` for a collection to both;
- `gh:site/nav/*.yml` 
- `gh:site/nav/` 

The screenshot below shows a commit result for each configuration, it appears that the `path` and file extension naming logic isn't working the same way when the `storage` is configured to use the local filesystem. 

<img width="818" alt="Screenshot 2024-03-12 at 6 47 37 AM" src="https://github.com/lumeland/cms/assets/32885/c7f9bf87-a491-4b7c-95d3-50d29a359016">

**Comment by oscarotero** [comment]
I see. FileSystem uses [glob](https://deno.land/std@0.219.0/fs/expand_glob.ts) to iterate and GitHub only the folder name. I think it's easy to implement a glob-like iterator for GitHub, using [glob_to_regexp](https://deno.land/std@0.219.0/path/glob_to_regexp.ts).

**Comment by revgum** [comment]
That'd be great, so the configuration would be the same using a glob pattern and the file created in the repo would end up in the proper location and with the proper file type?

**Comment by oscarotero** [comment]
Yes, that's the idea.

**Comment by oscarotero** [comment]
It seems easy to implement.
It's just checking the filename here https://github.com/lumeland/cms/blob/main/storage/github.ts#L61 and only yield it if the name match with the regular expression.

I'll do it today or tomorrow.

**Comment by oscarotero** [comment]
@revgum I just made some changes. Can you test it before releasing a new version?

**Comment by revgum** [comment]
@oscarotero Pretty close! The file was created properly, the commit message looks good.. but the route redirected to the full path (ie. `collection/nav/edit/src%2Fsite%2Fnav%2Ftesting-again.yml`) and when I fix the url to just `collection/nav/edit/testing-again.yml` the page works but the title filename is wrong.. 
<img width="483" alt="Screenshot 2024-03-12 at 10 48 08 AM" src="https://github.com/lumeland/cms/assets/32885/3aa3ff3a-6a7d-4fe0-a01e-0a126df19d80">

**Comment by revgum** [comment]
Because of the file naming issue, saving an update while editing the file fails because it is trying to find the incorrect file name in the repository. 
```
ERROR Error: 2024-03-12T23:57:59.251Z [POST] http://localhost:3000/cms/branch/preview/collection/nav/edit/src%2Fsite%2Fnav%2Fabout.yml - File not found: *.yml/src/site/nav/src/site/nav/about.yml
    at GitHub.delete 
    at eventLoopTick 
    at async GitHub.rename 
    at async Collection.rename 
    at async Object.handler 
```

**Comment by oscarotero** [comment]
I have updated a couple of fixes. Now it should work fine.
Can you confirm?
Thanks!

**Comment by revgum** [comment]
Works great, only one very minor issue that I see left.. The commit message for "Delete" doesn't appear to be using the `commitMessage` function, all I'm seeing for the message is "Delete file".

**Comment by oscarotero** [comment]
Good catch!
I had to change the `commitMessage` function to be able to use it everywhere. Let me know if it works to you.

**Comment by revgum** [comment]
Looks great and ready for a new release! Thank you!
