### ISSUE TITLE
Is it possible to use lume CLI to use the cms config to build the site?

### ISSUE THREAD

**Issue by revgum** [lumeland/cms#11]
I'd like to run `deno task lume cms --build` or something similar to build the site using the CMS configuration (storage configuration). My goal here is not to run the CMS, but to use its configuration for fetching the artifacts for lume to use to perform a build. 

It looks like the CMS lume adapter wants to use lume config (`_config.ts`) to build the site, and then use the CMS with `src` storage to watch files for changes to rebuild lume. 

I'd like to try to;

- Use lume CMS configuration to fetch all document, collection, etc from storage
- Use lume CLI to build the site using the data from the first step

**Comment by oscarotero** [comment]
Lume allows to add pages dynamically from the _config.ts file, I guess that could be possible.

The problem I see is the [cms content](https://github.com/lumeland/cms/blob/main/core/cms.ts#L125), is stored as a context variable in the Hono instance, I don't know if there's a way to access to this data from outside.

**Comment by revgum** [comment]
I'll keep pondering this as well as well. It seems like adding an option to CMS configuration to run an async bootstrap which populates the CMSContent `documents`, `collections` and `uploads`. 

Here's what I'm thinking;

- `Document` : Iterate over all [document configs fetching each from storage](https://github.com/lumeland/cms/blob/main/core/cms.ts#L167-L177) and populate `documents`.
- `Collection` : Iterate over all [collection configs](https://github.com/lumeland/cms/blob/main/core/cms.ts#L156-L165), and the iterate over the [collection async iterator](https://github.com/lumeland/cms/blob/main/core/collection.ts#L29-L33) and fetch all documents inside the collection, then populate `collections`.
- `Upload` : Iterate over all [upload configs](https://github.com/lumeland/cms/blob/main/core/cms.ts#L145-L154), and the iterate over [folders and fetch all uploads](https://github.com/lumeland/cms/blob/main/core/templates/uploads/list.ts) much like the template does, then populate `uploads`.

**Comment by oscarotero** [comment]
Okay, I've moved the content creation to a different function `initContent()`, so you can get it without init Hono:

```js
const content = cms.initContent();

const { documents, collections, uploads } = content;

for (const document of Object.entries(documents)) {
  console.log(await document.read());
}

for (const collection of Object.entries(collections)) {
  for (const { name } of collection) {
    const document = collection.get(name);
    console.log(await document.read());
  }
}

for (const upload of Object.entries(uploads)) {
  for (const { name } of upload) {
    const file = upload.get(name);
    console.log(await file.readFile());
  }
}
```

**Comment by revgum** [comment]
A minor fix to your example code here.. the `for (const { name } ....` lines should be `for await (const { name } ....` and this fetches all of the data for all of my documents, collections and uploads! Sweet.

I was poking around the `lume` repo trying to make more sense about how I'd use these within a `_config.ts`... or are you thinking something like;
- Fetch and write all of the files locally in a path
- Configure the lume build to use that path
- Build the site

**Comment by oscarotero** [comment]
Edited my previous comment with your fix.

Lume allows to create pages dynamically in the _config.ts. file with the `site.page()` function:

```js
site.page({
  url: "/final-url/",
  layout: "/post.vto",
  title: "Title of the post",
  // ...
});
```

One idea is to iterate the cms content to create pages for each document.

Another idea is using a generator page to create all pages out of the _config.ts. More info: https://lume.land/docs/core/multiple-pages/

**Comment by kylesloper** [comment]
Hi @oscarotero is cms.initContent() still available? Getting "cms.initContent is not a function" when trying to update from older version

**Comment by oscarotero** [comment]
@kylesloper Oh, sorry, I forgot about this. I'll restore it later.
