### ISSUE TITLE
Fields `type: "date"` in `type: "object-list"` don't get displayed

### ISSUE THREAD

**Issue by Steffo99** [lumeland/cms#15]
Can provide further information in a couple hours, if needed, just putting this here before I forget.

## Expected

![](https://github.com/lumeland/cms/assets/1540885/f7a3d21b-0306-4bf3-aef7-a0c8e04577de)

## Result

![](https://github.com/lumeland/cms/assets/1540885/18e4b2ca-2d1a-44e4-8e64-4e8f65691563)

## Version

v2.2.1

**Comment by oscarotero** [comment]
That's a bug. Thanks for reporting.

**Comment by oscarotero** [comment]
Fixed in v0.5.1

**Comment by Steffo99** [comment]
So fast! :heart: 

Thanks!
