### ISSUE TITLE
Tags label and description does not appear

### ISSUE THREAD

**Issue by RickCogley** [lumeland/cms#30]
I'm using v0.7.0 with latest lume, and the label and description have no effect. These never show up in the UI. 

I commented out the init, because when I add it (per the other closed issue I just commented on), it causes the pages to not be able to loaded into the editor. 

```
{
      name: "tags",
      type: "list",
      label: "Tags",
      description: "Tags to categorize the page",
      // init(field: any, { data }) {
      //   const site = data.site;
      //   const allTags = site.search.values("tags");
      //   field.options = allTags;
      // },
    },
```

**Comment by oscarotero** [comment]
The description wasn't shown due a bug that I just fixed it.
The label and init works fine to me (just checked them here https://github.com/lumeland/cms/blob/main/demo/dev.ts#L159)

**Comment by RickCogley** [comment]
Ok just to confirm, that style of init _does indeed_ work: 

```
      init(field) {
        field.options = ["tag1", "tag2", "tag3"];
      },
```

But this doesn't: 

```
{
      name: "tags",
      type: "list",
      label: "Tags",
      description: "Tags to categorize the page",
      init(field: any, { data }) {
        const site = data.site;
        const allTags = site.search.values("tags");
        field.options = allTags;
      },
    },
```

**Comment by RickCogley** [comment]
Not knowing whether tags can support Japanese or strings with spaces, I have both. Could that be the reason the above js that pulls in the list from the data object does not work? Maybe it's choking on spaces or unicode?

**Comment by RickCogley** [comment]
right, of course. I published to deno deploy and wondered why it doesn't work!
