### ISSUE TITLE
Number field type is an integer only

### ISSUE THREAD

**Issue by RickCogley** [lumeland/cms#32]
Not sure if this is a bug or feature, but the number field types accepts only integers, it appears. 

I tried using it to set priority for sitemap, but that needs 0 to 1, and values like 0.9 etc are ok in it. 

Hopefully the number field could be expanded or added to, to allow decimals.

**Comment by oscarotero** [comment]
By default, the number field type has the same configuration as [inputs of type number](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number).

> The default stepping value for number inputs is 1, allowing only integers to be entered—unless the stepping base is not an integer.

You can change the `step` attribute to allow decimals. For example:

```js
    {
      name: "priority",
      type: "number",
      attributes: {
        min: 0,
        max: 1,
        step: 0.1,
      },
    },
```

**Comment by RickCogley** [comment]
Wow, ok I'll try it!

**Comment by RickCogley** [comment]
thanks, just to close the loop: this worked perfectly
