### ISSUE TITLE
cms@v0.7.0 - Create Posts "There was an error. See logs for more info."

### ISSUE THREAD

**Issue by haturatu** [lumeland/cms#33]
When trying to create a new post with version 0.7.0 or above, this error occurs. 
  
"There was an error. See logs for more info."
![image](https://github.com/user-attachments/assets/2e767dd3-739d-4b8b-bc32-461eafeec656)
  
No error messages appear in the console. I’ve confirmed that it doesn’t happen with version 0.6.8. Is there any additional information I can provide, or are there any significant changes in version 0.7.0 or later?

**Comment by oscarotero** [comment]
Do you have any `init` callback in your cms configuration?

The signature has changed in 0.7.x:
https://lume.land/cms/configuration/fields/#the-init-function

**Comment by haturatu** [comment]
ah, it was because I hadn’t updated my `cms.collection`.   
https://github.com/lumeland/theme-simple-blog/blob/main/_cms.ts

I’m amazed at my own oversight...  
Thank you as always : )
