### ISSUE TITLE
Emit a configurable event when clicking "Save"

### ISSUE THREAD

**Issue by revgum** [lumeland/cms#6]
It would be great to have a couple of events emitted (to handle at the document/window) related to the user clicking "Save";

- An event that indicates that the save button was clicked and being processed
- An event that includes the status (success, error) when the save processed completes

My goal is to build some sort of additional UI, specific to my needs, that includes your CMS. I'd like to be able to handle events related to when a user clicks the save button and how it responds.

**Comment by oscarotero** [comment]
Why don't simply do this?

```js
const form = document.getElementById("form-edit");

form.addEventListener("submit", (ev) => {
  // Your callback here
});
```

**Comment by revgum** [comment]
Yea I was thinking about this as well, and is the direction I ended up going in the meantime. I was thinking about this feature in a bigger sense; introducing an event system for a variety of actions (the first being "save") that users could act on without having to bind directly to specific elements. What do you think?

**Comment by oscarotero** [comment]
I have to think about this. I'd like to keep the frontend architecture minimal, using web components and simple things, which is easy to maintain and with less bugs.

If you are thinking of something that benefits to all users, let me know. Maybe it can be added to the CMS.

**Comment by revgum** [comment]
That's a nice thing about emitting events, you can specify which and the data included. People can build components that react to the events if they want. I think it's a very low effort way to expose the life cycle of activity.

**Comment by oscarotero** [comment]
Can I know your use case? I'd like to understand what do you want to build, so I can think of a good solution.

**Comment by revgum** [comment]
I'm going to use the CMS, likely inside of of an iframe, and would like to bind to lifecycle events (something was saved) and then post messages for my app to react to. 

For instance, inside the CMS I'm using `extraHeads` to include some javascript which eventually just does `window.Top.postMessage` so that my app can act upon.

**Comment by oscarotero** [comment]
Why not the oposite? The CMS is designed to be the main app and preview the site in an iframe, not the other way around.
If you use Lume, the Lume adapter can do that. If you use a different generator, I think we can create an adapter for that.

**Comment by revgum** [comment]
I have a whole lot of additional UI, specific to my solution, where I want to use Lume CMS but integrate it into my front-end. Right now I plan on using the Github integration so there won't be a site preview. So the idea is that I would render Lume CMS inside of an iframe, and post messages to the parent frame so that I can do some UI behavior based on when the save button is clicked (or ideally, the states of when it is clicked and what the status of the save call was).

**Comment by revgum** [comment]
Also.. @oscarotero, I really appreciate the work you've done here and with Lume SSG! I hope my requests here aren't a big detour for your time and the project, I really like the foundation you've built already and it seems super close to serving my needs even as it stands! Truthfully, I could just target the form as-is and go from there.. I was thinking a little more broadly as a feature that the CMS might expose and benefit others as well.  <3

**Comment by oscarotero** [comment]
Don't worry, @revgum 
I like to understand how people use Lume and all the stress they apply to the sofware. It helps me to improve it and make it as most flexible as possible.

For now, if you can use the simple event listener to `#form-edit`, I'll keep as is.
I'd like to see the custom UI you're working on (if it's public), maybe some of them can be integrated in LumeCMS somehow.

For example, I'm thinking of showing more info of the collection documents in the list view (like title, image, etc), using optional settings.
